apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mischavandenburg/sb-llm-demo-backend:v0.3.1
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: llm-api-keys
