# NOTE: These must be set manually to the control plane IP addresses
# kubeEtcd:
#  endpoints:
#    - x.y.z.a
#    - x.y.z.b
#    - x.y.z.c
kubeControllerManager:
  service:
    selector:
      k8s-app: kube-controller-manager
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # Discover all PodMonitors, Probes, PrometheusRules and ServiceMonitors
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  grafana.ini:
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.basic:
      enabled: false
    auth.anonymous:
      enabled: true
    date_formats:
      default_week_start: monday

  # persistence:
  #   enabled: true
  #   type: pvc
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 4Gi
